[cursor]
unfocused_hollow = true

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"

[selection]
save_to_clipboard = true

[window]
opacity = 1

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [
  { key = "k", mods = "Alt", action = "ScrollLineUp" },
  { key = "j", mods = "Alt", action = "ScrollLineDown" },
]

[colors]
primary = { background = "#120E25" }

[colors.normal]
black = "#0B0C15"
red = "#D2556C"
green = "#7CD47B"
yellow = "#EFB184"
blue = "#6CA1F3"
magenta = "#B78DF0"
cyan = "#69BCF4"
white = "#BAC2DE"

[colors.bright]
black = "#39404A"
red = "#F7768E"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

